Feature and fix
ChocoDrusha/HomeWork1 pull request #2
Opened 2023-07-28 12:01 UTC by ChocoDrusha

2023-07-28 18:36 UTC, efpies requested changes

2023-07-28 18:36 UTC, efpies commented on Homework1/Services/DepositServices/BtcDepositService.cs
> +    public class BtcDepositService : ICryptoDepositService
Сервисы для BTC и RUB удивительно похожи.

2023-07-28 18:36 UTC, efpies commented on Homework1/Repositories/CurrencyRepository.cs
> +    public record CurrencyRepository
Странно называть опции репозиторием. Репозиторий предполагает какую-то логику.

2023-07-28 18:36 UTC, efpies commented on Homework1/Repositories/CurrencyRepository.cs
> +        //{
Комментированный код не надо коммитить.

2023-07-28 18:36 UTC, efpies commented on Homework1/Controllers/WalletController.cs
>                  var fiatModel = JsonSerializer.Deserialize<FiatDepositModel>(modelStr);
Класть модель из запроса прям в базу может быть несекурно, плюс у объекта в базе могут быть дополнительные поля или поля из запроса могут иметь другой формат.

DTO и Entity не нужно смешивать: это разные типы данных с разным поведением, даже если у них все поля будут совпадать (что для данного конкретно случая — вообще неправда, запрос и entity в базе различаются сильно).

Причём тут ещё и у объекта, приходящего с сервиса, будет поле GUID (которое генерируется при создании объекта, но не суть). Проставлением Identity должна заниматься БД, на крайний случай сервис, который будет создавать Entity для  вставки. В общем, это должно делаться централизованно. Здесь же нет никакой гарантии, что Id у модели будет разным для каждого объекта (кроме того, что это неявно подразумевается, но может измениться в любой момент, для чего придётся менять весь код, который с этим работает).

2023-07-28 18:36 UTC, efpies commented on Homework1/Controllers/WalletController.cs
>              return Ok();
Если у нас тип, который не поддерживается, тоже будет ok, хотя это ошибка.

2023-07-28 18:36 UTC, efpies commented on Homework1/Controllers/AdminController.cs
> +            user.IsBlocked = true;
В базе не обновляется блокировка.

2023-07-28 18:36 UTC, efpies commented on Homework1/Controllers/AdminController.cs
> +            sb.AppendLine(cryptoStr).AppendLine(fiatStr);
Кажется, это будет невалидный JSON.

2023-07-28 18:36 UTC, efpies commented on Homework1/Controllers/AdminController.cs
> +            var fiatDeposits = appDbContext.FiatDeposits.ToList();
А в чём смысл в разные таблицы фиат и крипту класть? У них большая часть полей одна, суть тоже одна.

2023-07-28 18:36 UTC, efpies commented on Homework1/JsonConverters/BalanceConverter.cs
> +    public class BalanceConverter : JsonConverter
Класс не используется.

2023-07-28 18:36 UTC, efpies commented on Homework1/Services/UserService.cs
> +                foreach (var i in _currencyRepository.Currencies)
Можно заменить на LINQ.

2023-07-28 18:36 UTC, efpies commented on Homework1/Services/UserService.cs
> +        public async Task<User> GetUser(string username)
Интерфейс предполагает not null, а FirstOrDefault может вернуть null.

2023-07-28 18:36 UTC, efpies commented on Homework1/Services/ExchangeRateGenerator.cs
> +            await using var scope = _scopeFactory.CreateAsyncScope();
Если у тебя цикл бесконечно крутится, это уже singleton, тут scope создавать смысла нет.

2023-07-28 18:36 UTC, efpies commented on Homework1/Services/ExchangeRateGenerator.cs
> +                    if (ratesRepository.Rates.ContainsKey(currency))
Можно сократить код в 4 раза:

```csharp

                    var rates = ratesRepository.Rates.GetValueOrDefault(currency, new List<RateModel>());
                    rates.Add(new RateModel
                    {
                        DateTime = DateTime.Now,
                        Rate = K
                    });
```

2023-08-06 07:42 UTC, ChocoDrusha commented on Homework1/Controllers/AuthController.cs
>              var a = claims.FirstOrDefault(o => o.Type == ClaimTypes.Name);
Исправил

2023-08-06 07:44 UTC, ChocoDrusha commented on Homework1/Controllers/WalletController.cs
>              return Ok();
Исправил

2023-08-07 23:06 UTC, ChocoDrusha commented on Homework1/bin/Debug/net6.0/Humanizer.dll
Исправлено

2023-08-07 23:06 UTC, ChocoDrusha commented on Homework1/JsonModels/config.json
> +    "UpdateTime": {
Исправлено

2023-08-07 23:07 UTC, ChocoDrusha commented on Homework1/Models/Balance.cs
> +        public Balance()
Исправлено

2023-08-07 23:07 UTC, ChocoDrusha commented on Homework1/JsonConverters/BalanceConverter.cs
> +    public class BalanceConverter : JsonConverter
Исправлено

2023-08-07 23:07 UTC, ChocoDrusha commented on Homework1/Services/UserService.cs
> +                foreach (var i in _currencyRepository.Currencies)
Исправлено

2023-08-07 23:07 UTC, ChocoDrusha commented on Homework1/Services/UserService.cs
> +        public async Task<User> GetUser(string username)
Исправлено

2023-08-07 23:07 UTC, ChocoDrusha commented on Homework1/Services/ExchangeRateGenerator.cs
> +                    if (ratesRepository.Rates.ContainsKey(currency))
Исправлено

2023-08-07 23:08 UTC, ChocoDrusha commented on Homework1/Repositories/CurrencyRepository.cs
> +    public record CurrencyRepository
Исправлено

2023-08-07 23:09 UTC, ChocoDrusha commented on Homework1/Controllers/AdminController.cs
> +            user.IsBlocked = true;
Исправлено

2023-08-07 23:09 UTC, ChocoDrusha commented on Homework1/Controllers/AdminController.cs
> +            var fiatDeposits = appDbContext.FiatDeposits.ToList();
А как иначе? Позволить некоторым полям быть null?

2023-08-08 15:40 UTC, efpies requested changes

2023-08-08 15:40 UTC, efpies commented on Homework1/Models/FiatDeposit.cs
> +            if (!(Amount is > 0.1m and < 100))
if (Amount is <= 0.1m or >= 100)

2023-08-08 15:40 UTC, efpies commented on Homework1/Models/CryptoDeposit.cs
> +            if (!(Amount is > 0.1m and < 100))
if (Amount is <= 0.1m or >= 100)

2023-08-08 15:40 UTC, efpies commented on Homework1/Controllers/AuthController.cs
> +        [HttpPost("/sign-up")]
/ в начале пути не надо писать. Он ничего не даёт, но затрудняет чтение.

2023-08-08 15:40 UTC, efpies commented on Homework1/Program.cs
> +builder.Services.AddScoped<IEnumerable<ICryptoDepositService>>(provider =>
IEnumerable добавлять не надо. Если ты просто сделаешь AddScoped<ICryptoDepositService, %service%> несколько раз, ты потом в DI сможешь получить IEnumerable<ICryptoDepositService>

2023-08-09 15:38 UTC, ChocoDrusha commented on Homework1/Controllers/AdminController.cs
> +            sb.AppendLine(cryptoStr).AppendLine(fiatStr);
Исправил

2023-08-12 12:19 UTC, ChocoDrusha commented on Homework1/Models/CryptoDeposit.cs
> +            if (!(Amount is > 0.1m and < 100))
Исправлено

2023-08-12 12:20 UTC, ChocoDrusha commented on Homework1/Controllers/AuthController.cs
> +        [HttpPost("/sign-up")]
Исправлено

2023-08-12 12:20 UTC, ChocoDrusha commented on Homework1/JsonModels/config.json
> +  "CurrencyConfig": {
Исправлено

2023-08-12 12:26 UTC, ChocoDrusha commented on Homework1/Services/TransactionsService.cs
> +            var transactions = new Transactions(cryptoDeposits, fiatDeposits);
Исправлено

2023-08-12 12:29 UTC, ChocoDrusha commented on Homework1/Services/InitDataService.cs
> +                var exists = await userService.GetUser(user.Username);
Исправлено

2023-08-12 12:30 UTC, ChocoDrusha commented on Homework1/Repositories/RatesRepository.cs
> +        public bool TryAddRate(string currency, RateModel rateModel)
Исправлено

2023-08-12 12:30 UTC, ChocoDrusha commented on Homework1/Models/FiatDeposit.cs
> +            if (!(Amount is > 0.1m and < 100))
Исправлено

2023-08-14 17:05 UTC, efpies commented on Homework1/Controllers/AdminController.cs
> +            var fiatDeposits = appDbContext.FiatDeposits.ToList();
У них есть общие поля, это будут колонки. Те поля, которые не совпадают, можно вынести в колонку типа JSON, в которую их и складывать (назвать AdditionalFields, например).

2023-08-14 17:07 UTC, efpies commented on Homework1/Services/InitDataService.cs
> +                var exists = await userService.GetUser(user.Username);
Не исправлено)

2023-08-14 17:08 UTC, efpies commented on Homework1/Repositories/RatesRepository.cs
> +        public bool TryAddRate(string currency, RateModel rateModel)
Не исправлено)

2023-09-09 06:54 UTC, ChocoDrusha commented on Homework1/Services/ExchangeRateGenerator.cs
> +            await using var scope = _scopeFactory.CreateAsyncScope();
Иначе всё ломается

2023-09-09 07:21 UTC, ChocoDrusha commented on Homework1/Services/ExchangeRateGenerator.cs
> +            await using var scope = _scopeFactory.CreateAsyncScope();
RatesRepository - scope сервис

2023-09-12 14:19 UTC, efpies commented on Homework1/Services/ExchangeRateGenerator.cs
> +            await using var scope = _scopeFactory.CreateAsyncScope();
Инжекти его в конструкторе из DI. Эффект будет тот же.

2023-09-12 14:25 UTC, efpies requested changes

2023-09-12 14:25 UTC, efpies commented on Homework1/Services/DepositServices/DepositService.cs
> +    public class DepositService : IDepositService
Этот класс должен быть абстрактным, т. к. если создать сервис такого типа, он не будет работать.

2023-09-12 14:25 UTC, efpies commented on Homework1/Services/DepositServices/DepositService.cs
> +        public UserService _userService { get; set; }
user service не должен торчать наружу, он вообще может быть приватным.

2023-09-12 14:25 UTC, efpies commented on Homework1/Services/DepositServices/BtcDepositService.cs
> +            this.Name = "btc";
Лучше сделать проперти Name abstract и заимплементить в каждом наследнике.

2023-09-12 14:25 UTC, efpies commented on Homework1/Services/DepositServices/BtcDepositService.cs
> +            _userService = userService;
Он и так проставляется в базовом классе.

2023-09-12 14:25 UTC, efpies commented on Homework1/Extensions/HttpClientExtensions.cs
> +    public static class HttpClientExtensions
Этот код к этому PR не относится, потому его тут быть не должно.

2023-09-12 14:25 UTC, efpies commented on Homework1/Program.cs
> +builder.Services.AddScoped<IDepositService, DepositService>();
Нет смысла добавлять пустой базовый класс в DI.

2023-09-13 07:32 UTC, merged