init commit
ChocoDrusha/HomeWork1 pull request #6
Opened 2023-10-03 14:37 UTC by ChocoDrusha

2023-10-03 14:55 UTC, efpies requested changes

2023-10-03 14:55 UTC, efpies commented on Homework1.Blazor/Pages/Index.razor
> +@*                <ul>
Комментированный код. Это вообще тут надо?

2023-10-03 14:55 UTC, efpies commented on Homework1.Blazor/Pages/Index.razor
> +        <h1>Hello, @context.User.Claims.FirstOrDefault(o => o.Type == ClaimTypes.Name).Value</h1>
Надо вынести в хелперы.

2023-10-03 14:55 UTC, efpies commented on Homework1.Blazor/Pages/Transactions.razor
> +            @if (UserRoleType == "User") {
Вместо этого IF можно в AuthorizeView прописать роли в Roles.

А вообще у тебя разметка совпадает, кроме некоторых полей. Вот эти отдельные компоненты и можно по разным ролям выводить, а не копипастить всё.

2023-10-03 14:55 UTC, efpies commented on Homework1.Blazor/Pages/Transactions.razor
> +            transactions = await TransactionsService.GetUserTransactions(UserId);
Код в if различается только этой строчкой.

2023-10-03 14:55 UTC, efpies commented on Homework1.Blazor/Pages/Transactions.razor
> +    private List<Homework1.Models.DepositModel> orderedTransactions { get; set; }
Чем тип данных тут отличается от предыдущего типа данных?

2023-10-03 14:55 UTC, efpies commented on Homework1.Blazor/Pages/Transactions.razor
> +        else if (UserRoleType == "Admin") {
Хардкод строк с ролями.

2023-10-03 14:55 UTC, efpies commented on Homework1.Blazor/Pages/Transactions.razor
> +                transactions.Deposits = transactions.Deposits.OrderByDescending(o => o.DateTime).ToList();
Все методы фильтрации транзакций должны быть централизованы, т. е. ты должен вызвать один метод filter в этом файле, который бы делал всю фильтрацию на основании текущих фильтров.

2023-10-03 18:19 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Transactions.razor
> +                transactions.Deposits = transactions.Deposits.OrderByDescending(o => o.DateTime).ToList();
фикс

2023-10-03 18:19 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Transactions.razor
> +    private List<Homework1.Models.DepositModel> orderedTransactions { get; set; }
фикс

2023-10-03 18:19 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Transactions.razor
> +            transactions = await TransactionsService.GetUserTransactions(UserId);
фикс

2023-10-03 18:19 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Transactions.razor
> +            @if (UserRoleType == "User") {
фикс

2023-10-03 18:19 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Index.razor
> +        <h1>Hello, @context.User.Claims.FirstOrDefault(o => o.Type == ClaimTypes.Name).Value</h1>
фикс

2023-10-03 18:19 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Index.razor
> +@*                <ul>
фикс

2023-10-03 18:32 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Transactions.razor
> +        else if (UserRoleType == "Admin") {
фикс

2023-10-03 18:39 UTC, efpies requested changes

2023-10-03 18:39 UTC, efpies commented on Homework1.Blazor/Pages/Transactions.razor
> +                    transactions = transactions.Where(o => o.IsApproved == status && o.User.Username.Contains(username) && o.Currency.Contains(currency)).OrderByDescending(o => o.DateTime).ToList();
Все эти фильтры должны применяться в БД. Например, если 100к записей, то в текущем подходе у тебя все они выгрузятся из БД и придут тебе. Это неэффективно. Плюс код очень сильно раздувается.

Логично у методов сервиса сделать nullable-параметры, применять LINQ-запросы

Типа

```
var txs = ....Transactions();

if (isApproved != null)
{
    txs = txs.Where(isApproved);
}

if (currency != null)
{
  txs = txs.Where(currency)
}
```

И так далее

2023-10-03 18:39 UTC, efpies commented on Homework1.Blazor/Pages/Transactions.razor
> +        else if (UserRoleType == "Admin") {
Хардкод не ушёл.

2023-10-03 19:16 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Transactions.razor
> +                    transactions = transactions.Where(o => o.IsApproved == status && o.User.Username.Contains(username) && o.Currency.Contains(currency)).OrderByDescending(o => o.DateTime).ToList();
фикс

2023-10-03 19:33 UTC, efpies requested changes

2023-10-03 19:33 UTC, efpies commented on Homework1.Blazor/Pages/UserTransactionsPage.razor
> +        var roleClaim = authState.User.FindFirst(o => o.Type == ClaimTypes.Role);
Тут вещи касательно получения полей юзера не вынесены.

2023-10-03 19:33 UTC, efpies commented on Homework1.Blazor/Pages/Transactions.razor
> +                            <tr style="background-color: #FA8072">
Дублируется вёрстка в if-else

2023-10-04 11:48 UTC, efpies requested changes

2023-10-04 11:48 UTC, efpies commented on Homework1/Models/CryptoDepositModel.cs
> +    public class CryptoDepositModel
Похоже, эти классы не нужны.

2023-10-04 11:48 UTC, efpies commented on Homework1/Validators/DepositValidator.cs
> +
Пустые строки не нужны.

2023-10-04 11:48 UTC, efpies commented on Homework1.Blazor/Shared/NavMenu.razor
> +            <div class="@NavMenuCssClass nav-scrollable" @onclick="ToggleNavMenu">
Дублируется вёрстка между ролями.

2023-10-04 11:48 UTC, efpies commented on Homework1.Blazor/Pages/Wallet.razor
> +@if (IsInitialized)
Рендер не вызовется до завершения инициализации, потому эта проверка не нужна, да и вообще эта переменная — тоже.

2023-10-04 11:48 UTC, efpies commented on Homework1.Blazor/Pages/Users.razor
> +                                <td>
У тебя 4 колонки контента и 3 колонки заголовков. Так работать не будет.

2023-10-04 11:48 UTC, efpies commented on Homework1.Blazor/Pages/Users.razor
> +            UsersList = AdminService.GetUsers().Where(o => o.Username.Contains(UsernameTextBox.Value)).ToList();
Почему ты вместо поля findUser смотришь в содержимое тестбокса?

2023-10-04 11:48 UTC, efpies commented on Homework1.Blazor/Pages/Users.razor
> +            UsersList = AdminService.GetUsers();
Можно также вынести фильтры в сервис.

2023-10-04 11:48 UTC, efpies commented on Homework1.Blazor/Pages/Users.razor
> +        UsersList = AdminService.GetUsers();
Это метод Find.

2023-10-04 11:48 UTC, efpies commented on Homework1.Blazor/Pages/UserPage.razor
> +            <h3>Id пользователя - @UserView.Role.ToString()</h3>
Не Id, а роль?

2023-10-04 12:06 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/UserPage.razor
> +            <h3>Id пользователя - @UserView.Role.ToString()</h3>
икс

2023-10-04 12:10 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Users.razor
> +                                <td>
фикс

2023-10-04 12:23 UTC, ChocoDrusha commented on Homework1.Blazor/Shared/NavMenu.razor
> +            <div class="@NavMenuCssClass nav-scrollable" @onclick="ToggleNavMenu">
фикс

2023-10-04 12:32 UTC, ChocoDrusha commented on Homework1/Models/CryptoDepositModel.cs
> +    public class CryptoDepositModel
фикс

2023-10-04 13:00 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Users.razor
> +            UsersList = AdminService.GetUsers();
фикс

2023-10-04 13:00 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Users.razor
> +        UsersList = AdminService.GetUsers();
фикс

2023-10-04 13:01 UTC, ChocoDrusha commented on Homework1/Validators/DepositValidator.cs
> +
фикс

2023-10-04 13:43 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Transactions.razor
> +                            <tr style="background-color: #FA8072">
фикс

2023-10-06 11:14 UTC, efpies requested changes

2023-10-06 11:14 UTC, efpies commented on Homework1.Blazor/Pages/Transactions.razor
> +        if (status is "true" or "false") {
Для таких полей нужно делать галочку, а не текстовое поле.

2023-10-06 21:06 UTC, efpies requested changes

2023-10-06 21:06 UTC, efpies commented on Homework1/Services/UserService.cs
> +            foreach (var currency in _currencyRepository.Currencies)
Можно сделать просто .Select из LINQ.

2023-10-06 21:06 UTC, efpies commented on Homework1/Services/UserService.cs
> +                    userBalance.Balance = balance.Value;
Если default вернёт null, то этот код упадёт. Вообще, в таких случаях лучше через словарь это делать (currency-balance), а перед возвратом делать List из этого.

2023-10-06 21:06 UTC, efpies commented on Homework1/Services/TransactionsService.cs
> +            if (status.HasValue && status != DepositStatusType.None)
Код для get transactions во многом повторяется, хотя это +/- один код, просто с доп. условиями.

2023-10-06 21:13 UTC, ChocoDrusha commented on Homework1/Constants/DepositConstant.cs
> +        public const string CONFIRMED_COLOR = "#8cff81";
исправил

2023-10-06 21:13 UTC, ChocoDrusha commented on Homework1/Models/DepositModel.cs
> +        public DepositModel() { }
исправил

2023-10-06 21:14 UTC, ChocoDrusha commented on Homework1/Models/DepositStatusType.cs
> +        public static string ToString(this DepositStatusType statusType)
исправил

2023-10-06 21:14 UTC, ChocoDrusha commented on Homework1/Models/DepositStatusType.cs
> +    public static class ErrorLevelExtensions
исправил

2023-10-06 21:15 UTC, ChocoDrusha commented on Homework1/Services/TransactionsService.cs
> +                deposits = deposits.OrderByDescending(o => o.DateTime).ToList();
исправил

2023-10-06 22:23 UTC, efpies requested changes

2023-10-06 22:23 UTC, efpies commented on Homework1/Services/TransactionsService.cs
> +            query.OrderByDescending(o => o.DateTime).ToList();
Эта строка ничего не делает. Ты не сохраняешь результаты запроса. И зачем-то делаешь ToList синхронно. Нужно делать query = query.Order...

2023-10-06 22:23 UTC, efpies commented on Homework1/Constants/ColorConstant.cs
> +        public const string CONFIRMED_COLOR = "#8cff81";
Опять же, эти константы у тебя — в проекте API, они к нему не имеют отношения. И вообще они должны быть в CSS, который относится к модулю, а в коде тебе надо только class менять у тега.

2023-10-06 22:23 UTC, efpies commented on Homework1/Extensions/DepositTypeExtensions.cs
> +        public static string ToUIString(this DepositStatusType statusType)
Также не имеет отношения к API.

2023-10-06 22:23 UTC, efpies commented on Homework1/Extensions/StringExtensions.cs
> +    public static class StringExtensions
Это, скорее, DepositStatusType extensions.

2023-10-06 22:23 UTC, efpies commented on Homework1.Blazor/Pages/Transactions.razor
> +        statusType = status.GetDepositType();
Превращать UI-строку в enum — это очень плохая идея. Лучше в dropdown иметь item-ы, у которых есть value = enum/константу и текст = UI-строке. Тогда тип сразу будет правильный без конверсий.

2023-10-06 23:20 UTC, ChocoDrusha commented on Homework1.Blazor/Pages/Transactions.razor
> +        statusType = status.GetDepositType();
фикс

2023-10-06 23:20 UTC, ChocoDrusha commented on Homework1/Extensions/StringExtensions.cs
> +    public static class StringExtensions
фикс

2023-10-06 23:20 UTC, ChocoDrusha commented on Homework1/Extensions/DepositTypeExtensions.cs
> +        public static string ToUIString(this DepositStatusType statusType)
фикс

2023-10-06 23:20 UTC, ChocoDrusha commented on Homework1/Constants/ColorConstant.cs
> +        public const string CONFIRMED_COLOR = "#8cff81";
фикс

2023-10-06 23:20 UTC, ChocoDrusha commented on Homework1/Services/TransactionsService.cs
> +            query.OrderByDescending(o => o.DateTime).ToList();
фикс

2023-10-06 23:20 UTC, ChocoDrusha commented on Homework1/Services/TransactionsService.cs
> +            if (status.HasValue && status != DepositStatusType.None)
фикс

2023-10-06 23:20 UTC, ChocoDrusha commented on Homework1/Services/UserService.cs
> +                    userBalance.Balance = balance.Value;
фикс

2023-10-06 23:20 UTC, ChocoDrusha commented on Homework1/Services/UserService.cs
> +            foreach (var currency in _currencyRepository.Currencies)
фикс

2023-10-06 23:20 UTC, ChocoDrusha commented on Homework1/Services/UserService.cs
> +            return res;
фикс

2023-10-06 23:20 UTC, ChocoDrusha commented on Homework1/Services/TransactionsService.cs
> +            await appDbContext.SaveChangesAsync();
фикс

2023-10-09 19:18 UTC, merged